name: auto-version

on:

  push:
    branches: [ main ]    

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0

      - name: Reset Origin
        run: |
          git remote set-url origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/serverlessworkflow/synapse.git"
          git checkout ${{ github.ref_name }}
#   github.actor will be the account how will perform the push (or most of the case 'merge pull request').
#   secrets.GITHUB_TOKEN must be a token for the github.actor.
#   github.ref_name work fine if the trigger was a push.  

      - name: Install Versioning.NET
        run: |
          dotnet tool install --global Versioning.NET
          
      - name: Increment Version
        run: |
          dotnet-version increment-version-with-git -g "." --branch-name ${{ github.ref_name }} --author-email actions@github.com
